apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    openshift.io/required-scc: ebs-metrics-exporter
    openshift.io/scc: ebs-metrics-exporter
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    openshift.io/description: "Provide EBS volume performance metrics via Prometheus"
  labels:
    app.kubernetes.io/component: ebs-metrics-exporter
    app.kubernetes.io/name: ebs-metrics-exporter
  name: ebs-metrics-exporter
  namespace: openshift-sre-ebs-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: ebs-metrics-exporter
      app.kubernetes.io/name: ebs-metrics-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ebs-metrics-exporter
        app.kubernetes.io/name: ebs-metrics-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: ebs-metrics-exporter
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - operator: Exists
      containers:
      - name: ebs-metrics-exporter
        image: REPLACE_IMAGE
        imagePullPolicy: Always
        command:
        - /ebs-metrics-collector
        args:
        - --device=$(EBS_DEVICE)
        - --port=8090
        env:
        - name: EBS_DEVICE
          value: "/dev/nvme1n1"
        ports:
        - name: metrics
          containerPort: 8090
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: true
          runAsUser: 0
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - name: dev
          mountPath: /dev
          readOnly: true
      volumes:
      - name: dev
        hostPath:
          path: /dev
          type: Directory
